# Generated by Django 3.2.3 on 2021-09-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_about_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='assets')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=400)),
                ('twitter', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('insta', models.CharField(max_length=100)),
                ('linkdln', models.CharField(max_length=100)),
            ],
        ),
    ]
