# Generated by Django 3.2.3 on 2021-09-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_about_img1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='assets')),
                ('address', models.CharField(max_length=200)),
                ('phone', models.IntegerField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('insta', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('linkdln', models.CharField(max_length=100)),
            ],
        ),
    ]
