# Generated by Django 3.2.3 on 2021-09-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
