# Generated by Django 3.2.3 on 2021-09-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_other_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
