# Generated by Django 3.2.3 on 2021-09-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_events_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=1000)),
                ('father', models.CharField(max_length=100)),
                ('aadhar', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='assets')),
            ],
        ),
        migrations.CreateModel(
            name='Student_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mother', models.CharField(max_length=100)),
                ('father', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=1000)),
                ('phone', models.CharField(max_length=100)),
                ('standerd', models.CharField(max_length=100)),
                ('aadhar', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('pre_standerd', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='assets')),
            ],
        ),
    ]
