# Generated by Django 3.2.3 on 2021-09-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_faculty_detail_student_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_detail',
            name='img',
            field=models.ImageField(default='static/img/logo.png', upload_to='assets'),
        ),
        migrations.AlterField(
            model_name='student_detail',
            name='img',
            field=models.ImageField(default='static/img/logo.png', upload_to='assets'),
        ),
    ]
