# Generated by Django 3.2.3 on 2021-09-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_auto_20210914_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_detail',
            name='img',
            field=models.ImageField(default='static/img/logo.png', upload_to=''),
        ),
    ]
