# Generated by Django 3.2.3 on 2021-09-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_alter_faculty_detail_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_structure', models.FileField(upload_to='assets')),
                ('book_syllabus', models.FileField(upload_to='assets')),
                ('course', models.FileField(upload_to='assets')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='assets')),
            ],
        ),
    ]
