# Generated by Django 3.2.4 on 2021-09-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_detail',
            name='fee_status',
            field=models.TextField(default='0', max_length=10000),
        ),
    ]
